vich_uploader:
    db_driver: orm

    mappings:
        ads:
            uri_prefix: '%uploaded%'
            upload_destination: '%kernel.project_dir%/public/%uploaded%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
